### ISSUE TITLE
Document that ImageMagick is required for gif output ?

### ISSUE THREAD

**Issue by ederag** [cesaraustralia/DynamicGrids.jl#181]
The "Forest Fire" example
<details>
 <summary>code</summary>

```julia
using DynamicGrids, ColorSchemes, Colors, BenchmarkTools

const DEAD, ALIVE, BURNING = 1, 2, 3

neighbors_rule = let prob_combustion=0.0001, prob_regrowth=0.01
    Neighbors(Moore(1)) do data, neighborhood, cell, I
        if cell == ALIVE
            if BURNING in neighborhood
                BURNING
            else
                rand() <= prob_combustion ? BURNING : ALIVE
            end
        elseif cell == BURNING
            DEAD
        else
            rand() <= prob_regrowth ? ALIVE : DEAD
        end
    end
end

# Set up the init array and output (using a Gtk window)
init = fill(ALIVE, 400, 400)
output = GifOutput(init; 
    filename="forestfire.gif", tspan=1:200, fps=25, 
    minval=DEAD, maxval=BURNING, 
    imagegen=Image(scheme=ColorSchemes.rainbow, zerocolor=RGB24(0.0))
)

# Run the simulation, which will save a gif when it completes
sim!(output, neighbors_rule)
```

</details>

fails with 
```julia
Error encountered while save FileIO.File{FileIO.DataFormat{:GIF}, String}("forestfire.gif").

Fatal error:
ERROR: LoadError: ArgumentError: Package ImageMagick [6218d12a-5da1-5696-b52f-db25d2ecc6d1] is required 
but does not seem to be installed
```

No big deal, but adding a comment line such as 
`# ImageMagick will be needed by FileIO to provide the gif output`,
below the `using` line (listing the required packages) or before `GifOutput`, might be nice.

Side note: I considered filing a PR instead, but the "Edit on Github" button points to
https://github.com/cesaraustralia/DynamicGrids.jl/blob/master/docs/src/index.md,
where that code is not found.

**Comment by rafaqz** [comment]
Thanks, yes I should mention that. Just happens that I'm editing tt right now too!

FileIO does some tricky things so you could use another backend like https://github.com/JuliaIO/ImageIO.jl - that's why it isn't a direct dependency - it's also nice not to require ImageMagick.jl for non-visual simulations e.g. on servers.

And yes you wont see that code at the link because that example is actually currently in the README.md - which gets brought in as the main module docs for DynamicGrids.jl. The edit link in the docs isn't that useful generally... it only really gives you access to the overview and structure. Mostly the actual docs are generated from inline docstring for each individual type/function and in this case the module. These are mixed into the code.

**Comment by ederag** [comment]
Thanks for the explanations, agreed.
Please do close when you think it's fine.

**Comment by rafaqz** [comment]
Cheers, I've already edited your comment into the example in my working branch, so I'll close now.
