### ISSUE TITLE
Error running readme example: MethodError: no method matching sim!

### ISSUE THREAD

**Issue by yarkun** [cesaraustralia/DynamicGrids.jl#200]
Hello,

When I try to run the Life() example from the readme, I get two warnings and an error:

[Log at 2022-01-05 22-45-22.txt](https://github.com/cesaraustralia/DynamicGrids.jl/files/7817423/Log.at.2022-01-05.22-45-22.txt)

I am using Julia 1.7.1 on macOS 10.15.7, in iTerm2 Build 3.4.14.

Regards,

**Comment by rafaqz** [comment]
Thanks! But I can't reproduce this, your example works fine on the latest version. But you seem to be using very old packages? What is the output of `] status DynamicGrids`

Second, when including code in a github issue, please make an inline code block like this:

```julia
using DynamicGrids, Crayons
init = rand(Bool, 150, 200)
output = REPLOutput(init; tspan=1:200, fps=30, color=Crayon(foreground=:red, background=:black, bold=true))
sim!(output, Life())
```

And a separate block with the error code. That way i can just run it, instead of searching through the whole file.

**Comment by yarkun** [comment]
Hello,
You were right, I was trying to run an embarrassingly old version of DynamicGrids, even though I added the package last week. The example is running fine with the updated packages. I am sorry about the beginner mistake.
Regards,

**Comment by rafaqz** [comment]
No worries! Feel free to make an issue for any problem you have getting things working, its good to know what people have problems with.
