### ISSUE TITLE
Rename Overflow/overflow= to BoundaryCondition/boundary=

### ISSUE THREAD

**Issue by rafaqz** [cesaraustralia/DynamicGrids.jl#83]
Attempting to clean up the language I have used before the 1.0 release.

@jamesmaino and @virgile-baudrot your input on this would be appreciated!

ImageFiltering uses the term Boundaries, and these names:

>Symbol must be on one of:
    :replicate (repeat edge values to infinity),
    :circular (image edges "wrap around"),
    :symmetric (the image reflects relative to a position between pixels),
    :reflect (the image reflects relative to the edge itself).

https://juliaimages.org/ImageFiltering.jl/stable/function_reference/#Boundaries-and-padding-1

We will use types so you can add methods with dispatch, and we need additional options like just removing anything that crosses the boundary. I also have been using verbs where ImagFiltering uses nouns. Either are fine. 

But the options could be:

```julia
abstract type BoundaryCondition end
struct Remove <: BoundaryCondition end
struct Cycle <: BoundaryCondition end # better than Wrap I think?
struct Wall <: BoundaryCondition end # virgiles proposal in #75 

sim!(output, rule; boundary=Cycle())
```

Thoughts?

**Comment by jamesmaino** [comment]
I like the descriptions and names used by ImageFiltering. Though if you continue with our current types, I like "wrap" better than "cycle". But I think the short descriptions are more important than the name.

**Comment by rafaqz** [comment]
We have those descriptions too ;)

```julia
help?> WrapOverflow
search: WrapOverflow

  struct WrapOverflow <: Overflow

  WrapOverflow()

  Wrap cordinates that overflow boundaries back to the opposite side of the grid.
```

This is mostly about using `Boundary` instead of `Overflow` - does that make sense?

**Comment by rafaqz** [comment]
We could also use :symbols instead of types - the problem is you lose dispatch, so you you cant write a new boundary condition without forking the package.

**Comment by jamesmaino** [comment]
The struct sounds more flexible, optimised and is the same in compactness. Unless I'm still misunderstanding?

**Comment by rafaqz** [comment]
Yeah - the only problem is it pollutes the namespace a tiny bit more.

And, are you ok with with chainging the abstract type to  `Boundary`, with `boundary` as the keyword argument? is there a better word than boundary for this?

**Comment by virgile-baudrot** [comment]
Yes, I like `Boundary` rather than `Overflow` since boundary condition is used in differential equation theory, and it seems also to be the case in image processing. So yes `Boundary` type and `boundary` as keyword argument is perfect.

About choosing types vs :symbol, I understand the latter make sense if we already define an exhaustive list (or almost). If this list can be infinite, then types is preferable. Theoretically, there are an infinity of boundary conditions, but I feel like there is a narrow limited number that really make sense and are going to be used. So, I don't know.

About their naming, I don't have a strong legitimacy  to debat about vocabulary :-). I think `circular` is because of cycle in Fourier transform used in convolution process and dispersal. But, since you use verb, I like `wrap`.

**Comment by virgile-baudrot** [comment]
If I'm right, `overflow` was to define within `Ruleset` step. Did you think moving it in the `sim` step, or maybe it was already possible to use `overflow` in both `ruleset` and `sim`?

Because, in `sim!(output, rule; boundary=Cycle())`, it means that all rules follow the same boundary condition? I realize it was probably already the case if we define it at `ruleset`...

I see situations where rules with different boundary conditions could make sense (e.g., propagules spread out over seas compared to terrestrial animals) . Then, I don't know the cost of such possiblity?

**Comment by rafaqz** [comment]
Ok Boundary it is. I was thinking the same about using symbols - there are only a limited set of boundary conditions you would actually use. But I haven't actually defined them all at this stage! We could allow both and define symbols for the options we have currently. It would still be struct internally because it has to be type stable.

You can actually pass in rules without a Rulesetm and pass any of the ruleset keyword args to `sim!` at the same time. But you can't if it's already a ruleset, as I don't bother to rebuild it with the new options. Maybe that should work too, but probably low priority.
https://github.com/cesaraustralia/DynamicGrids.jl/blob/master/src/framework.jl#L75-L88

**Comment by rafaqz** [comment]
To be clear we can also use nouns like ImageFiltering does, the current names are basically what I randomly chose right at the start, there was no real reason to them.

**Comment by virgile-baudrot** [comment]
Ok, I had a look. Names are ok for me.
Just you export two times `isinferred`
